from __future__ import annotations

import argparse
from pathlib import Path

from ai_native.factory_runner.schema_generation import (
    SCHEMA_SET_DIGEST_FILENAME,
    schema_artifact_drift,
    write_schema_artifacts,
)
from ai_native.factory_runner.schema_registry import CONTRACT_SCHEMAS


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPOSITORY_ROOT / "ai_native" / "schemas" / "factory_runner" / "v1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic factory-runner-protocol/v1 schemas.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail if checked-in schema artifacts differ from generated bytes",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="write generated schema artifacts (the default)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="override the schema output directory",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    if not args.check:
        write_schema_artifacts(output_dir)

    differences = schema_artifact_drift(output_dir)
    if differences:
        print("factory runner schema drift detected:")
        for difference in differences:
            print(f"- {difference}")
        return 1

    digest = (
        (output_dir / SCHEMA_SET_DIGEST_FILENAME).read_text(encoding="ascii").strip()
    )
    action = "verified" if args.check else "generated"
    print(
        f"{action} {len(CONTRACT_SCHEMAS)} factory runner schemas; schema set {digest}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
